# Generated by Django 3.2.5 on 2021-07-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAttitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField()),
                ('q2', models.CharField(max_length=100)),
                ('q3', models.BooleanField()),
                ('q4', models.CharField(max_length=100)),
                ('q5', models.CharField(max_length=20)),
                ('q6', models.CharField(max_length=100)),
                ('q7', models.CharField(max_length=100)),
                ('q8', models.CharField(max_length=100)),
                ('q9', models.CharField(max_length=100)),
                ('q10', models.CharField(max_length=100)),
                ('q11', models.BooleanField()),
                ('q12', models.BooleanField()),
                ('q13', models.CharField(max_length=20)),
                ('q14', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('qualification', models.CharField(max_length=50)),
                ('income_range', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marital_status', models.BooleanField()),
                ('q1', models.BooleanField()),
                ('q2', models.CharField(max_length=20)),
                ('q3', models.CharField(max_length=20)),
                ('q4', models.BooleanField()),
                ('q5', models.CharField(max_length=20)),
                ('q6', models.CharField(max_length=20)),
                ('q7', models.BooleanField()),
                ('q8', models.CharField(max_length=20)),
                ('q9', models.CharField(max_length=20)),
                ('q10', models.CharField(max_length=20)),
            ],
        ),
    ]
