# Generated by Django 3.2.6 on 2021-08-19 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorAttitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('q1', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('q2', models.CharField(max_length=500)),
                ('q3', models.SmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True)),
                ('q4', models.CharField(blank=True, max_length=500, null=True)),
                ('q5', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('liver', 'Liver')], max_length=24, null=True)),
                ('q6', models.CharField(blank=True, max_length=500, null=True)),
                ('q7', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('liver', 'Liver')], max_length=24, null=True)),
                ('q8', models.CharField(blank=True, max_length=100, null=True)),
                ('q9', models.CharField(blank=True, max_length=500, null=True)),
                ('q10', models.CharField(blank=True, max_length=500, null=True)),
                ('q11', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('q12', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('q13', models.CharField(blank=True, max_length=200, null=True)),
                ('q14', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
            ],
        ),
        migrations.CreateModel(
            name='DonorKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('qualification', models.CharField(choices=[('Basic', 'Basic Level'), ('Secondary', 'Secondary Level'), ('Tertiary', 'Tertiary Level')], max_length=50)),
                ('marital_status', models.IntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced')])),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('q1', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('q2', multiselectfield.db.fields.MultiSelectField(choices=[('Radio/TV', 'Radio/TV'), ('Social Media', 'Social Media'), ('News Papers', 'News Papers')], max_length=33)),
                ('q3', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('q4', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('q5', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('q6', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('q7', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('q8', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('q9', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('q10', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('level', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.champion')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
