# Generated by Django 3.2.5 on 2021-07-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyAttitude',
            new_name='DonorAttitude',
        ),
        migrations.RenameModel(
            old_name='SurveyKnowledge',
            new_name='DonorKnowledge',
        ),
    ]
