# Generated by Django 3.2.6 on 2021-08-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorattitude',
            name='q15',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
