# Generated by Django 3.2.6 on 2021-09-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donorattitude_q15'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.champion')),
            ],
        ),
    ]
