# Generated by Django 3.2.5 on 2021-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210729_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
