# Generated by Django 3.2.5 on 2021-07-14 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210714_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorattitude',
            name='date_complete',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorknowledge',
            name='date_complete',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
