# Generated by Django 3.2.5 on 2021-07-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20210714_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorattitude',
            old_name='date_complete',
            new_name='date_completed',
        ),
        migrations.RenameField(
            model_name='donorknowledge',
            old_name='date_complete',
            new_name='date_completed',
        ),
    ]
