# Generated by Django 3.2.5 on 2021-07-15 10:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20210714_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorknowledge',
            name='q5',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('liver', 'Liver')], max_length=24),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q7',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('liver', 'Liver')], max_length=24),
        ),
    ]
