# Generated by Django 3.2.6 on 2021-10-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_donorattitude_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorattitude',
            name='consent_after_quiz',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
