# Generated by Django 3.2.5 on 2021-07-15 11:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_auto_20210715_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorattitude',
            name='q5',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('liver', 'Liver')], max_length=24),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q7',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('liver', 'Liver')], max_length=24),
        ),
    ]
