# Generated by Django 3.2.6 on 2021-10-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_donorattitude_consent_after_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorattitude',
            name='conset_after_story',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
