# Generated by Django 3.2.5 on 2021-07-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_auto_20210715_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorKnowledge',
        ),
    ]
