# Generated by Django 3.2.6 on 2021-10-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_donorattitude_conset_after_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorattitude',
            old_name='conset_after_story',
            new_name='consent_after_story',
        ),
    ]
