# Generated by Django 3.2.5 on 2021-07-15 12:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_delete_donorknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('qualification', models.CharField(max_length=50)),
                ('income_range', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marital_status', models.BooleanField()),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('q1', models.BooleanField()),
                ('q2', models.CharField(max_length=20)),
                ('q3', models.CharField(max_length=20)),
                ('q4', models.BooleanField()),
                ('q5', multiselectfield.db.fields.MultiSelectField(choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('liver', 'Liver')], max_length=24)),
                ('q6', models.CharField(max_length=20)),
                ('q7', multiselectfield.db.fields.MultiSelectField(choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('liver', 'Liver')], max_length=24)),
                ('q8', models.CharField(max_length=20)),
                ('q9', models.CharField(max_length=20)),
                ('q10', models.CharField(max_length=20)),
            ],
        ),
    ]
