# Generated by Django 3.2.6 on 2021-10-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_rename_conset_after_story_donorattitude_consent_after_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorattitude',
            name='consent_after_reward',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
