# Generated by Django 3.2.5 on 2021-07-15 12:18

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_donorknowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorknowledge',
            name='marital_status',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced')]),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q10',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Radio/TV', 'Radio/TV'), ('Social Media', 'Social Media'), ('News Papers', 'News Papers')], max_length=33),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q3',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q5',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q6',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q7',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q8',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q9',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='qualification',
            field=models.CharField(choices=[('Basic', 'Basic Level'), ('Secondary', 'Secondary Level'), ('Tertiary', 'Tertiary Level')], max_length=50),
        ),
    ]
