# Generated by Django 3.2.5 on 2021-07-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_auto_20210715_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorknowledge',
            name='income_range',
        ),
    ]
