# Generated by Django 3.2.6 on 2021-10-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_remove_story_champion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
