# Generated by Django 3.2.5 on 2021-07-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_auto_20210722_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorknowledge',
            name='q1',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q10',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q3',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q4',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q5',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q6',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q7',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q8',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q9',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
    ]
