# Generated by Django 3.2.6 on 2021-10-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_alter_story_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorattitude',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='donorattitude',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='donorattitude',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='donorattitude',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='donorattitude',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='donorattitude',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='donorattitude',
            name='q9',
        ),
    ]
