# Generated by Django 3.2.5 on 2021-07-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0012_auto_20210724_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorattitude',
            name='q1',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q11',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q12',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q14',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q3',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
    ]
