# Generated by Django 3.2.6 on 2021-10-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0013_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorattitude',
            name='why_consent',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
