# Generated by Django 3.2.5 on 2021-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0013_auto_20210726_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorknowledge',
            name='survey_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
