# Generated by Django 3.2.5 on 2021-07-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0014_donorknowledge_survey_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorknowledge',
            old_name='survey_id',
            new_name='visitor_id',
        ),
        migrations.AddField(
            model_name='donorattitude',
            name='visitor_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
