# Generated by Django 3.2.6 on 2021-10-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0014_donorattitude_why_consent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorattitude',
            old_name='why_consent',
            new_name='consent_msg',
        ),
    ]
