# Generated by Django 3.2.6 on 2021-10-14 16:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0016_donorattitude_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorknowledge',
            name='q2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Radio/TV', 'Radio/TV'), ('Social Media', 'Social Media'), ('News Papers', 'News Papers')], max_length=33, null=True),
        ),
    ]
