# Generated by Django 3.2.5 on 2021-07-27 21:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0016_auto_20210727_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorattitude',
            name='q10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q13',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q3',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q5',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('liver', 'Liver')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q7',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('liver', 'Liver')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
