# Generated by Django 3.2.6 on 2021-10-25 17:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0017_alter_donorknowledge_q2'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorattitude',
            name='no_consent_msg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='donorknowledge',
            name='q2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Radio/TV', 'Radio/TV'), ('Social Media', 'Social Media'), ('News Papers', 'News Papers'), ('Web', 'The web')], max_length=37, null=True),
        ),
    ]
