# Generated by Django 3.2.5 on 2021-07-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0017_auto_20210727_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorattitude',
            name='q10',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donorattitude',
            name='q9',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
