# Generated by Django 3.2.6 on 2021-10-27 11:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0018_auto_20211025_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorknowledge',
            name='q2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Radio/TV', 'Radio/TV'), ('Social Media', 'Social Media'), ('News Papers', 'News Papers'), ('Internet', 'Internet')], max_length=42, null=True),
        ),
    ]
