# Generated by Django 3.2.6 on 2021-10-27 11:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0019_alter_donorknowledge_q2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorknowledge',
            name='q2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Radio/TV', 'Radio/TV'), ('Social Media', 'Social Media'), ('Internet', 'Internet'), ('News Papers', 'News Papers')], max_length=42, null=True),
        ),
    ]
