# Generated by Django 3.2.6 on 2021-10-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0020_alter_donorknowledge_q2'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorknowledge',
            name='age',
            field=models.IntegerField(choices=[(1, '18-24 years'), (2, '25-34 years'), (3, '35-44 years'), (4, '45-54 years'), (5, '55 years or older')], default=1),
            preserve_default=False,
        ),
    ]
