# Generated by Django 3.2.6 on 2021-09-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='score',
            field=models.IntegerField(),
        ),
    ]
