# Generated by Django 3.2.5 on 2021-07-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-name',), 'verbose_name_plural': 'Quizes'},
        ),
    ]
