# Generated by Django 3.2.5 on 2021-07-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='With supporting text below as a natural lead-in to additional content.', max_length=1000),
            preserve_default=False,
        ),
    ]
