# Generated by Django 3.2.5 on 2021-07-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='long_text',
            field=models.TextField(default='Long explanation of question'),
            preserve_default=False,
        ),
    ]
