# Generated by Django 3.2.5 on 2021-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.AddField(
            model_name='result',
            name='visitor_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
